# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/alexanderlapygin.com
cert = /etc/letsencrypt/live/alexanderlapygin.com/cert.pem
privkey = /etc/letsencrypt/live/alexanderlapygin.com/privkey.pem
chain = /etc/letsencrypt/live/alexanderlapygin.com/chain.pem
fullchain = /etc/letsencrypt/live/alexanderlapygin.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 0846ddfa11037668f0851c2f323c6179
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
