server {
    server_name  mind-section.com  www.mind-section.com;

    root   /var/www/mind-section.com/html;
    index  index.html index.htm;

    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /var/www/mind-section.com/html;   # тот же root, что и у сайта
        allow all;
        auth_basic off;   # если стоит базовая авторизация
    }

    # редирект всего SPA на index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # сжатие
    gzip on;
    gzip_types text/plain text/css application/json application/javascript
               text/xml application/xml application/xml+rss text/javascript;

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mind-section.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mind-section.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.mind-section.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = mind-section.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name  mind-section.com  www.mind-section.com;
    return 404; # managed by Certbot




}